# Generated by Django 4.0.3 on 2022-03-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_club_product_club'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='club',
            new_name='clubname',
        ),
    ]
