# Generated by Django 4.0.3 on 2022-07-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_alter_clubname_club_name_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='relatedproducts',
            field=models.ManyToManyField(blank=True, null=True, to='shop.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
