# Generated by Django 4.0.3 on 2022-07-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_relatedproducts_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hot_deal',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
