# Generated by Django 4.0.3 on 2022-07-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
