# Generated by Django 4.0.3 on 2022-07-12 04:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_blog_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
