# Generated by Django 4.0.3 on 2022-07-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_blog_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='sub_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
