# Generated by Django 4.0.3 on 2022-07-16 08:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_blog_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
