# Generated by Django 4.0.3 on 2022-07-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_customer_order_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='province',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='ward',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
