# Generated by Django 4.0.3 on 2022-07-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_rename_province_shippingaddress_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='order_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
